version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-10.13.0
    steps:
      - checkout
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Install project dependencies
          command: npm i
      - run:
          name: Run Tests
          command: npm run test:ci

